[package]
name = "clman"
version = "0.1.0"
authors = ["Keyvan Kambakhsh <keyvankambakhsh@gmail.com>"]
description = "OpenCL Package Manager"
edition = "2018"

[dependencies]
ocl = "0.19"
yaml-rust = "0.4"
clap = "2.33.1"
thiserror = "1.0.10"
