---
version: 0.1.0

define:
  JULIA_REAL: $0
  JULIA_IMAG: $1
  WIDTH: 2560
  HEIGHT: 1600
  WORK_SIZE: $(($WIDTH * $HEIGHT))

src:
  define.cl:
    code: "#define JULIA_C (float2)($JULIA_REAL, $JULIA_IMAG)"
  color.cl:
    path: src/color.cl
  complex.cl:
    path: src/complex.cl
  main.cl:
    path: src/main.cl

buffers:
  output:
    type: float4
    count: $WORK_SIZE

jobs:
  fill_img:
    run: draw
    args:
      - buffer: output
      - uint: $WIDTH
      - uint: $HEIGHT
    global_work_size: $WORK_SIZE

  save_img:
    save: output
    to:
      type: image
      path: output.jpg
      x: $WIDTH
      y: $HEIGHT
